
export default [
  {
    name: 'AFGHANISTAN',
    code: 'afg',
  }, {
    name: 'ALBANIA',
    code: 'alb',
  }, {
    name: 'ALGERIA',
    code: 'alg',
  }, {
    name: 'AMERICAN SAMOA',
    code: 'asa',
  }, {
    name: 'ANDORRA',
    code: 'and',
  }, {
    name: 'ANGOLA',
    code: 'ang',
  }, {
    name: 'ANTIGUA AND BARBUDA',
    code: 'ant',
  }, {
    name: 'ARGENTINA',
    code: 'arg',
  }, {
    name: 'ARMENIA',
    code: 'arm',
  }, {
    name: 'ARUBA',
    code: 'aru',
  }, {
    name: 'AUSTRALIA',
    code: 'aus',
  }, {
    name: 'AUSTRIA',
    code: 'aut',
  }, {
    name: 'AZERBAIJAN',
    code: 'aze',
  }, {
    name: 'BAHAMAS',
    code: 'bah',
  }, {
    name: 'BAHRAIN',
    code: 'brn',
  }, {
    name: 'BANGLADESH',
    code: 'ban',
  }, {
    name: 'BARBADOS',
    code: 'bar',
  }, {
    name: 'BELARUS',
    code: 'blr',
  }, {
    name: 'BELGIUM',
    code: 'bel',
  }, {
    name: 'BELIZE',
    code: 'biz',
  }, {
    name: 'BENIN',
    code: 'ben',
  }, {
    name: 'BERMUDA',
    code: 'ber',
  }, {
    name: 'BHUTAN',
    code: 'bhu',
  }, {
    name: 'BOLIVIA',
    code: 'bol',
  }, {
    name: 'BOSNIA AND HERZEGOVINA',
    code: 'bih',
  }, {
    name: 'BOTSWANA',
    code: 'bot',
  }, {
    name: 'BRAZIL',
    code: 'bra',
  }, {
    name: 'BRUNEI DARUSSALAM',
    code: 'bru',
  }, {
    name: 'BULGARIA',
    code: 'bul',
  }, {
    name: 'BURKINA FASO',
    code: 'bur',
  }, {
    name: 'BURUNDI',
    code: 'bdi',
  }, {
    name: 'CAMBODIA',
    code: 'cam',
  }, {
    name: 'CAMEROON',
    code: 'cmr',
  }, {
    name: 'CANADA',
    code: 'can',
  }, {
    name: 'CAPE VERDE',
    code: 'cpv',
  }, {
    name: 'CAYMAN ISLANDS',
    code: 'cay',
  }, {
    name: 'CENTRAL AFRICAN REPUBLIC',
    code: 'caf',
  }, {
    name: 'CHAD',
    code: 'cha',
  }, {
    name: 'CHILE',
    code: 'chi',
  }, {
    name: 'CHINESE TAIPEI',
    code: 'tpe',
  }, {
    name: 'COLOMBIA',
    code: 'col',
  }, {
    name: 'COMOROS',
    code: 'com',
  }, {
    name: 'CONGO',
    code: 'cgo',
  }, {
    name: 'COOK ISLANDS',
    code: 'cok',
  }, {
    name: 'COSTA RICA',
    code: 'crc',
  }, {
    name: 'CÔTE D\'IVOIRE',
    code: 'civ',
  }, {
    name: 'CROATIA',
    code: 'cro',
  }, {
    name: 'CUBA',
    code: 'cub',
  }, {
    name: 'CYPRUS',
    code: 'cyp',
  }, {
    name: 'CZECH REPUBLIC',
    code: 'cze',
  }, {
    name: 'DEMOCRATIC PEOPLE\'S REPUBLIC OF KOREA',
    code: 'prk',
  }, {
    name: 'DEMOCRATIC REPUBLIC OF THE CONGO',
    code: 'cod',
  }, {
    name: 'DENMARK',
    code: 'den',
  }, {
    name: 'DJIBOUTI',
    code: 'dji',
  }, {
    name: 'DOMINICAN REPUBLIC',
    code: 'dom',
  }, {
    name: 'DOMINIQUE',
    code: 'dma',
  }, {
    name: 'ECUADOR',
    code: 'ecu',
  }, {
    name: 'EGYPT',
    code: 'egy',
  }, {
    name: 'EL SALVADOR',
    code: 'esa',
  }, {
    name: 'EQUATORIAL GUINEA',
    code: 'geq',
  }, {
    name: 'ERITREA',
    code: 'eri',
  }, {
    name: 'ESTONIA',
    code: 'est',
  }, {
    name: 'ESWATINI',
    code: 'swz',
  }, {
    name: 'ETHIOPIA',
    code: 'eth',
  }, {
    name: 'FEDERATED STATES OF MICRONESIA',
    code: 'fsm',
  }, {
    name: 'FIJI',
    code: 'fij',
  }, {
    name: 'FINLAND',
    code: 'fin',
  }, {
    name: 'FRANCE',
    code: 'fra',
  }, {
    name: 'GABON',
    code: 'gab',
  }, {
    name: 'GAMBIA',
    code: 'gam',
  }, {
    name: 'GEORGIA',
    code: 'geo',
  }, {
    name: 'GERMANY',
    code: 'ger',
  }, {
    name: 'GHANA',
    code: 'gha',
  }, {
    name: 'GREAT BRITAIN',
    code: 'gbr',
  }, {
    name: 'GREECE',
    code: 'gre',
  }, {
    name: 'GRENADA',
    code: 'grn',
  }, {
    name: 'GUAM',
    code: 'gum',
  }, {
    name: 'GUATEMALA',
    code: 'gua',
  }, {
    name: 'GUINEA',
    code: 'gui',
  }, {
    name: 'GUINEA-BISSAU',
    code: 'gbs',
  }, {
    name: 'GUYANA',
    code: 'guy',
  }, {
    name: 'HAITI',
    code: 'hai',
  }, {
    name: 'HONDURAS',
    code: 'hon',
  }, {
    name: 'HONG KONG, CHINA',
    code: 'hkg',
  }, {
    name: 'HUNGARY',
    code: 'hun',
  }, {
    name: 'ICELAND',
    code: 'isl',
  }, {
    name: 'INDIA',
    code: 'ind',
  }, {
    name: 'INDONESIA',
    code: 'ina',
  }, {
    name: 'IRAQ',
    code: 'irq',
  }, {
    name: 'IRELAND',
    code: 'irl',
  }, {
    name: 'ISLAMIC REPUBLIC OF IRAN',
    code: 'iri',
  }, {
    name: 'ISRAEL',
    code: 'isr',
  }, {
    name: 'ITALY',
    code: 'ita',
  }, {
    name: 'JAMAICA',
    code: 'jam',
  }, {
    name: 'JAPAN',
    code: 'jpn',
  }, {
    name: 'JORDAN',
    code: 'jor',
  }, {
    name: 'KAZAKHSTAN',
    code: 'kaz',
  }, {
    name: 'KENYA',
    code: 'ken',
  }, {
    name: 'KIRIBATI',
    code: 'kir',
  }, {
    name: 'KOSOVO',
    code: 'kos',
  }, {
    name: 'KUWAIT',
    code: 'kuw',
  }, {
    name: 'KYRGYZSTAN',
    code: 'kgz',
  }, {
    name: 'LAO PEOPLE\'S DEMOCRATIC REPUBLIC',
    code: 'lao',
  }, {
    name: 'LATVIA',
    code: 'lat',
  }, {
    name: 'LEBANON',
    code: 'lbn',
  }, {
    name: 'LESOTHO',
    code: 'les',
  }, {
    name: 'LIBERIA',
    code: 'lbr',
  }, {
    name: 'LIBYA',
    code: 'lba',
  }, {
    name: 'LIECHTENSTEIN',
    code: 'lie',
  }, {
    name: 'LITHUANIA',
    code: 'ltu',
  }, {
    name: 'LUXEMBOURG',
    code: 'lux',
  }, {
    name: 'MADAGASCAR',
    code: 'mad',
  }, {
    name: 'MALAWI',
    code: 'maw',
  }, {
    name: 'MALAYSIA',
    code: 'mas',
  }, {
    name: 'MALDIVES',
    code: 'mdv',
  }, {
    name: 'MALI',
    code: 'mli',
  }, {
    name: 'MALTA',
    code: 'mlt',
  }, {
    name: 'MARSHALL ISLANDS',
    code: 'mhl',
  }, {
    name: 'MAURITANIA',
    code: 'mtn',
  }, {
    name: 'MAURITIUS',
    code: 'mri',
  }, {
    name: 'MEXICO',
    code: 'mex',
  }, {
    name: 'MONACO',
    code: 'mon',
  }, {
    name: 'MONGOLIA',
    code: 'mgl',
  }, {
    name: 'MONTENEGRO',
    code: 'mne',
  }, {
    name: 'MOROCCO',
    code: 'mar',
  }, {
    name: 'MOZAMBIQUE',
    code: 'moz',
  }, {
    name: 'MYANMAR',
    code: 'mya',
  }, {
    name: 'NAMIBIA',
    code: 'nam',
  }, {
    name: 'NAURU',
    code: 'nru',
  }, {
    name: 'NEPAL',
    code: 'nep',
  }, {
    name: 'NETHERLANDS',
    code: 'ned',
  }, {
    name: 'NEW ZEALAND',
    code: 'nzl',
  }, {
    name: 'NICARAGUA',
    code: 'nca',
  }, {
    name: 'NIGER',
    code: 'nig',
  }, {
    name: 'NIGERIA',
    code: 'ngr',
  }, {
    name: 'NORWAY',
    code: 'nor',
  }, {
    name: 'OMAN',
    code: 'oma',
  }, {
    name: 'PAKISTAN',
    code: 'pak',
  }, {
    name: 'PALAU',
    code: 'plw',
  }, {
    name: 'PALESTINE',
    code: 'ple',
  }, {
    name: 'PANAMA',
    code: 'pan',
  }, {
    name: 'PAPUA NEW GUINEA',
    code: 'png',
  }, {
    name: 'PARAGUAY',
    code: 'par',
  }, {
    name: 'PEOPLE\'S REPUBLIC OF CHINA',
    code: 'chn',
  }, {
    name: 'PERU',
    code: 'per',
  }, {
    name: 'PHILIPPINES',
    code: 'phi',
  }, {
    name: 'POLAND',
    code: 'pol',
  }, {
    name: 'PORTUGAL',
    code: 'por',
  }, {
    name: 'PUERTO RICO',
    code: 'pur',
  }, {
    name: 'QATAR',
    code: 'qat',
  }, {
    name: 'REPUBLIC OF KOREA',
    code: 'kor',
  }, {
    name: 'REPUBLIC OF MOLDOVA',
    code: 'mda',
  }, {
    name: 'ROMANIA',
    code: 'rou',
  }, {
    name: 'RUSSIAN FEDERATION',
    code: 'rus',
  }, {
    name: 'RWANDA',
    code: 'rwa',
  }, {
    name: 'SAINT KITTS AND NEVIS',
    code: 'skn',
  }, {
    name: 'SAINT LUCIA',
    code: 'lca',
  }, {
    name: 'SAMOA (UNTIL 1996 WESTERN SAMOA)',
    code: 'sam',
  }, {
    name: 'SAN MARINO',
    code: 'smr',
  }, {
    name: 'SAO TOME AND PRINCIPE',
    code: 'stp',
  }, {
    name: 'SAUDI ARABIA',
    code: 'ksa',
  }, {
    name: 'SENEGAL',
    code: 'sen',
  }, {
    name: 'SERBIA',
    code: 'srb',
  }, {
    name: 'SEYCHELLES',
    code: 'sey',
  }, {
    name: 'SIERRA LEONE',
    code: 'sle',
  }, {
    name: 'SINGAPORE',
    code: 'sgp',
  }, {
    name: 'SLOVAKIA',
    code: 'svk',
  }, {
    name: 'SLOVENIA',
    code: 'slo',
  }, {
    name: 'SOLOMON ISLANDS',
    code: 'sol',
  }, {
    name: 'SOMALIA',
    code: 'som',
  }, {
    name: 'SOUTH AFRICA',
    code: 'rsa',
  }, {
    name: 'SOUTH SUDAN',
    code: 'ssd',
  }, {
    name: 'SPAIN',
    code: 'esp',
  }, {
    name: 'SRI LANKA',
    code: 'sri',
  }, {
    name: 'ST VINCENT AND THE GRENADINES',
    code: 'vin',
  }, {
    name: 'SUDAN',
    code: 'sud',
  }, {
    name: 'SURINAME',
    code: 'sur',
  }, {
    name: 'SWEDEN',
    code: 'swe',
  }, {
    name: 'SWITZERLAND',
    code: 'sui',
  }, {
    name: 'SYRIAN ARAB REPUBLIC',
    code: 'syr',
  }, {
    name: 'TAJIKISTAN',
    code: 'tjk',
  }, {
    name: 'THAILAND',
    code: 'tha',
  }, {
    name: 'THE FORMER YUGOSLAV REPUBLIC OF MACEDONIA',
    code: 'mkd',
  }, {
    name: 'TIMOR-LESTE',
    code: 'tls',
  }, {
    name: 'TOGO',
    code: 'tog',
  }, {
    name: 'TONGA',
    code: 'tga',
  }, {
    name: 'TRINIDAD AND TOBAGO',
    code: 'tto',
  }, {
    name: 'TUNISIA',
    code: 'tun',
  }, {
    name: 'TURKEY',
    code: 'tur',
  }, {
    name: 'TURKMENISTAN',
    code: 'tkm',
  }, {
    name: 'TUVALU',
    code: 'tuv',
  }, {
    name: 'UGANDA',
    code: 'uga',
  }, {
    name: 'UKRAINE',
    code: 'ukr',
  }, {
    name: 'UNITED ARAB EMIRATES',
    code: 'uae',
  }, {
    name: 'UNITED REPUBLIC OF TANZANIA',
    code: 'tan',
  }, {
    name: 'UNITED STATES OF AMERICA',
    code: 'usa',
  }, {
    name: 'URUGUAY',
    code: 'uru',
  }, {
    name: 'UZBEKISTAN',
    code: 'uzb',
  }, {
    name: 'VANUATU',
    code: 'van',
  }, {
    name: 'VENEZUELA',
    code: 'ven',
  }, {
    name: 'VIETNAM',
    code: 'vie',
  }, {
    name: 'VIRGIN ISLANDS, BRITISH',
    code: 'ivb',
  }, {
    name: 'VIRGIN ISLANDS, US',
    code: 'isv',
  }, {
    name: 'YEMEN',
    code: 'yem',
  }, {
    name: 'ZAMBIA',
    code: 'zam',
  }, {
    name: 'ZIMBABWE',
    code: 'zim',
  },
];
